global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'k8s-gpu-management'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['k8s-gpu-app:8080']
    scrape_interval: 30s